name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Спрацьовує, коли ти робиш пуш у гілку main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # Для Create React App це зазвичай 'build', для Vite - 'dist'
          branch: gh-pages # Гілка, де буде жити готовий сайт
